### ISSUE TITLE
Move setInterval to componentDidMount.

### ISSUE THREAD

**Issue by JohnFrolov** [irizz/test#1]
https://github.com/irizz/test/blob/45f354e5aa6f3af37feb8ba108d0957da5138cc9/src/index.js#L13-L19

SetInterval is kind of subscription. xD
This method is a good place to set up any subscriptions. If you do that, don’t forget to unsubscribe in <strong>componentWillUnmount().</strong>

**Comment by irizz** [comment]
Done, componentWillUnmount() added as well.
